# Site settings
title: Zeta-Two.com
email: calle.svensson@zeta-two.com
description: > # Site description
  My blog about technology, security and life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zeta-two.com" # the base hostname & protocol for your site
twitter_username: zetatwo
github_username:  ZetaTwo

# Build settings
markdown: kramdown
highlighter: rouge
encoding: utf-8
paginate: 5
exclude: ['Gemfile.lock', 'Gemfile', 'src/']
#paginate_path: "/blog/page:num/"

disqusid: zetatwo

katex:
    path_to_js: "./assets/katex/katex.min.js"