# Site settings
title: Zeta-Two.com
email: calle.svensson@zeta-two.com
description: > # Site description
  My blog about technology, security and life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://zeta-two.com" # the base hostname & protocol for your site
twitter_username: zetatwo
github_username:  ZetaTwo

# Build settings
plugins: ['jekyll-paginate', 'jekyll-katex']
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables", "footnotes"]
highlighter: rouge
encoding: utf-8
paginate: 5
exclude: ['Gemfile.lock', 'Gemfile', 'src/', 'LICENSE', 'README.md', 'butlerfile']
#paginate_path: "/blog/page:num/"

disqusid: zetatwo
theme: jekyll-theme-zetatwo
timezone: Europe/Stockholm

katex:
  js_path: "assets/katex"  # Path used to search for katex.min.js
  rendering_options:
    # Default KaTeX rendering options. See https://github.com/Khan/KaTeX#rendering-options
    throw_error: true                       # throwOnError - set to false if you want rendering to output error as text rather than a build error
    error_color: "#cc0000"                  # errorColor

click_to_play_video: false
