version: 0.2
   
phases:
  install:
    runtime-versions:
        ruby: 2.6
        nodejs: 10
    commands:
      - gem install bundler
      - bundle install
  build:
    commands:
      - bundle exec jekyll build
      - aws s3 sync --delete _site/ s3://www.zeta-two.com
